In [1]:
import pandas as pd
import numpy as np

In [98]:
def get_Seq_array(seqlist,k):
    listlen = len(seqlist)
    movavg = listlen-k+1
    n=0
    j=k
    m=[]
    while(n<j):
        addnum=0
        for i in range(n,j):
            addnum = addnum + seqlist[i]
        else:
            addnum = addnum/k
            m.append(addnum)
            n=n+1
            j=j+1
            if(n==listlen-(k-1)):
                break
    return np.array(m,dtype=int)

In [101]:
get_Seq_array([10,20,30,40,50,60,70,80,90,100],4)

array([25, 35, 45, 55, 65, 75, 85])

In [102]:
get_Seq_array([3,5,7,2,8,10,11,65,72,81,99,100,150],3)

array([  5,   4,   5,   6,   9,  28,  49,  72,  84,  93, 116])

In [336]:
def geo_progress(firstrow,inpvector,arraysize):
    m=[]
    c=firstrow
    d=inpvector
    k=0
    while(k<(arraysize-1)):
        if m==[]:
            m.append(c)
        
        n=[]
        arr = np.array(m,dtype=object)
        vec = np.array([d],dtype=object)
        f=arr.shape
        g=f[0]
        e = arr[g-1] * vec
        n = e.tolist()
        m.append(n[0])
        b=np.array(m,dtype=object)
        
        k=k+1


    return b.T

In [337]:
geo_progress([2,4,6,8],[1,2,3,4],4)

array([[2, 2, 2, 2],
       [4, 8, 16, 32],
       [6, 18, 54, 162],
       [8, 32, 128, 512]], dtype=object)